name: Docker Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest  # , l5, self-hosted
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Build Docker image (manual)
      run: run.sh