name: Docker Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3    
    - name: Build Docker image (manual)
      run: ./run.sh