name: run.sh

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: macos-latest 
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3 
      
    -
      name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v3    
      # uses: crazy-max/ghaction-setup-containerd@v3
      
    # - name: Build Docker image (manual)
    #   run: ./run.sh

    - name: Build Docker image (manual)
      run: docker build -t my-docker-image .
