name: run.sh

on:
  push

jobs:
  build:
    runs-on: macos-latest 
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3    
    - name: Build Docker image (manual)
      run: ./run.sh
